#!/usr/bin/env python3
"""
Regression test: an alt haplotype of your own chromosome is not another chromosome.

From results/REAL_PATIENT_DATA_VALIDATION.md finding 8.

hs38DH carries alt haplotypes and unlocalised scaffolds named after their
primary chromosome. Comparing raw contig names counted a mate on chr15's OWN
alt haplotype as an inter-chromosomal event: on chr15_KI270905v1_alt the
largest single mate partner was chr15 itself, producing discordant fractions
of 0.172 and 0.223 at MAPQ 60 and composite scores of 32.5 "weak" and 40.0
"moderate" — translocation-shaped evidence generated by routine alt-aware
mapping.

The grouping decides discordance only. The exact contig is still what gets
reported, so nothing is blurred in the output.

KNOWN CAVEAT, asserted below so it stays visible: the 525 HLA-* contigs
belong to the MHC on chr6, but their names encode no such link. Mapping them
would mean hardcoding a guess, so a mate on an HLA contig is still counted as
inter-chromosomal. That is a documented limitation, not an oversight.

Run: python3 stage1_igv_assistant/tests/test_alt_contig_pairs.py
"""
import os
import sys
import tempfile

import pysam

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

from stage1_igv_assistant.tools.bam_tools import (  # noqa: E402
    _primary_contig,
    count_discordant_pairs,
)

FAILURES = []

HEADER = pysam.AlignmentHeader.from_dict({
    "HD": {"VN": "1.6", "SO": "coordinate"},
    "SQ": [{"SN": "chr15", "LN": 1000000},
           {"SN": "chr15_KI270905v1_alt", "LN": 500000},
           {"SN": "chr15_KI270727v1_random", "LN": 400000},
           {"SN": "chrUn_KI270302v1", "LN": 200000},
           {"SN": "HLA-DRB1*01:01:01", "LN": 110000},
           {"SN": "chr8", "LN": 900000}],
})
IDX = {sq["SN"]: i for i, sq in enumerate(HEADER.to_dict()["SQ"])}


def check(label, condition, detail=""):
    if condition:
        print(f"  PASSED ✓  {label}")
    else:
        print(f"  FAILED ✗  {label}\n             {detail}")
        FAILURES.append(label)


def _bam(path, mate_contig, n=40):
    with pysam.AlignmentFile(path, "wb", header=HEADER) as bam:
        for i in range(n):
            r = pysam.AlignedSegment(HEADER)
            r.query_name = f"r{i}"
            r.query_sequence = "A" * 100
            r.flag = 0x1
            r.reference_id = 0                     # always on chr15
            r.reference_start = 10000 + i * 5
            r.mapping_quality = 60
            r.cigar = [(0, 100)]
            r.next_reference_id = IDX[mate_contig]
            r.next_reference_start = 100000
            r.query_qualities = pysam.qualitystring_to_array("I" * 100)
            bam.write(r)
    pysam.index(path)
    return path


def run_tests():
    print("=" * 68)
    print("ALT CONTIG PAIRING REGRESSION SUITE")
    print("=" * 68)
    tmp = tempfile.mkdtemp()

    print("\n_primary_contig maps only the well-defined chrN_* pattern")
    for name, expect in [("chr15_KI270905v1_alt", "chr15"),
                         ("chr1_KI270706v1_random", "chr1"),
                         ("chrX_KI270880v1_alt", "chrX"),
                         ("chr15", "chr15"), ("chrM", "chrM"),
                         ("chrUn_KI270302v1", "chrUn_KI270302v1"),
                         ("HLA-DRB1*01:01:01", "HLA-DRB1*01:01:01")]:
        check(f"{name!r} -> {expect!r}", _primary_contig(name) == expect,
              f"got {_primary_contig(name)!r}")

    print("\na mate on your own alt haplotype is NOT discordant")
    for contig in ["chr15_KI270905v1_alt", "chr15_KI270727v1_random"]:
        r = count_discordant_pairs(_bam(os.path.join(tmp, "a.bam"), contig),
                                   "chr15", 10100, min_mapq=20)
        check(f"mate on {contig}: discordant_pairs == 0",
              r["discordant_pairs"] == 0, f"got {r['discordant_pairs']}")
        check(f"mate on {contig}: counted as same_primary_alt instead",
              r["same_primary_alt_mates"] == 40,
              f"got {r['same_primary_alt_mates']}")
        check(f"mate on {contig}: not reported as a partner chromosome",
              r["mate_chromosomes"] == {}, f"got {r['mate_chromosomes']}")

    print("\na mate on a genuinely different chromosome still is discordant")
    r = count_discordant_pairs(_bam(os.path.join(tmp, "b.bam"), "chr8"),
                               "chr15", 10100, min_mapq=20)
    check("mate on chr8: discordant_pairs == 40",
          r["discordant_pairs"] == 40, f"got {r['discordant_pairs']}")
    check("mate on chr8: the EXACT contig is reported, not the primary",
          r["mate_chromosomes"] == {"chr8": 40}, f"got {r['mate_chromosomes']}")
    check("mate on chr8: not counted as same_primary_alt",
          r["same_primary_alt_mates"] == 0, f"got {r['same_primary_alt_mates']}")

    print("\nan alt of a DIFFERENT chromosome is still discordant")
    alt_other = count_discordant_pairs(
        _bam(os.path.join(tmp, "c.bam"), "chrUn_KI270302v1"), "chr15", 10100, min_mapq=20)
    check("mate on chrUn_* has no primary to merge with, stays discordant",
          alt_other["discordant_pairs"] == 40, f"got {alt_other['discordant_pairs']}")
    check("and is reported under its exact name",
          "chrUn_KI270302v1" in alt_other["mate_chromosomes"],
          f"got {alt_other['mate_chromosomes']}")

    print("\nKNOWN CAVEAT: HLA contigs are not mapped to chr6")
    hla = count_discordant_pairs(_bam(os.path.join(tmp, "d.bam"), "HLA-DRB1*01:01:01"),
                                 "chr15", 10100, min_mapq=20)
    check("an HLA mate is still counted as inter-chromosomal (documented limitation)",
          hla["discordant_pairs"] == 40, f"got {hla['discordant_pairs']}")
    check("the caveat is recorded in the source",
          "KNOWN CAVEAT" in open(
              os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "..", "tools", "bam_tools.py"), encoding="utf-8").read(),
          "no caveat note found next to _primary_contig")

    print("\n" + "=" * 68)
    if FAILURES:
        print(f"{len(FAILURES)} FAILURE(S)")
        for f in FAILURES:
            print(f"  - {f}")
        sys.exit(1)
    print("ALL ALT CONTIG PAIRING TESTS PASSED")
    print("=" * 68)


if __name__ == "__main__":
    run_tests()
